<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $paises = [
            // --- Países Prioritarios ---
            ['nombre' => 'México', 'nombre_en' => 'Mexico', 'codigo_iso' => 'MX', 'prioritario' => true, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Estados Unidos', 'nombre_en' => 'United States', 'codigo_iso' => 'US', 'prioritario' => true, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Canadá', 'nombre_en' => 'Canada', 'codigo_iso' => 'CA', 'prioritario' => true, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],

            // --- Otros Países ---
            ['nombre' => 'Afganistán', 'nombre_en' => 'Afghanistan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Albania', 'nombre_en' => 'Albania', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Alemania', 'nombre_en' => 'Germany', 'codigo_iso' => 'DE', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Andorra', 'nombre_en' => 'Andorra', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Angola', 'nombre_en' => 'Angola', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Antigua y Barbuda', 'nombre_en' => 'Antigua and Barbuda', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Arabia Saudita', 'nombre_en' => 'Saudi Arabia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Argelia', 'nombre_en' => 'Algeria', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Argentina', 'nombre_en' => 'Argentina', 'codigo_iso' => 'AR', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Armenia', 'nombre_en' => 'Armenia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Australia', 'nombre_en' => 'Australia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Austria', 'nombre_en' => 'Austria', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Azerbaiyán', 'nombre_en' => 'Azerbaijan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bahamas', 'nombre_en' => 'Bahamas', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bangladés', 'nombre_en' => 'Bangladesh', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Barbados', 'nombre_en' => 'Barbados', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Baréin', 'nombre_en' => 'Bahrain', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bélgica', 'nombre_en' => 'Belgium', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Belice', 'nombre_en' => 'Belize', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Benín', 'nombre_en' => 'Benin', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bielorrusia', 'nombre_en' => 'Belarus', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Birmania', 'nombre_en' => 'Myanmar', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bolivia', 'nombre_en' => 'Bolivia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bosnia y Herzegovina', 'nombre_en' => 'Bosnia and Herzegovina', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Botsuana', 'nombre_en' => 'Botswana', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Brasil', 'nombre_en' => 'Brazil', 'codigo_iso' => 'BR', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Brunéi', 'nombre_en' => 'Brunei', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bulgaria', 'nombre_en' => 'Bulgaria', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Burkina Faso', 'nombre_en' => 'Burkina Faso', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Burundi', 'nombre_en' => 'Burundi', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Bután', 'nombre_en' => 'Bhutan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Cabo Verde', 'nombre_en' => 'Cape Verde', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Camboya', 'nombre_en' => 'Cambodia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Camerún', 'nombre_en' => 'Cameroon', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Chad', 'nombre_en' => 'Chad', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Chile', 'nombre_en' => 'Chile', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'China', 'nombre_en' => 'China', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Chipre', 'nombre_en' => 'Cyprus', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Colombia', 'nombre_en' => 'Colombia', 'codigo_iso' => 'CO', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Comoras', 'nombre_en' => 'Comoros', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Costa Rica', 'nombre_en' => 'Costa Rica', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Costa de Marfil', 'nombre_en' => 'Ivory Coast', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Croacia', 'nombre_en' => 'Croatia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Cuba', 'nombre_en' => 'Cuba', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Dinamarca', 'nombre_en' => 'Denmark', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Dominica', 'nombre_en' => 'Dominica', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Ecuador', 'nombre_en' => 'Ecuador', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Egipto', 'nombre_en' => 'Egypt', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'El Salvador', 'nombre_en' => 'El Salvador', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Emiratos Árabes Unidos', 'nombre_en' => 'United Arab Emirates', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Eritrea', 'nombre_en' => 'Eritrea', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Eslovaquia', 'nombre_en' => 'Slovakia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Eslovenia', 'nombre_en' => 'Slovenia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'España', 'nombre_en' => 'Spain', 'codigo_iso' => 'ES', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Estonia', 'nombre_en' => 'Estonia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Etiopía', 'nombre_en' => 'Ethiopia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Filipinas', 'nombre_en' => 'Philippines', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Finlandia', 'nombre_en' => 'Finland', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Fiyi', 'nombre_en' => 'Fiji', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Francia', 'nombre_en' => 'France', 'codigo_iso' => 'FR', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Gabón', 'nombre_en' => 'Gabon', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Gambia', 'nombre_en' => 'Gambia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Georgia', 'nombre_en' => 'Georgia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Ghana', 'nombre_en' => 'Ghana', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Granada', 'nombre_en' => 'Grenada', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Grecia', 'nombre_en' => 'Greece', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Guatemala', 'nombre_en' => 'Guatemala', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Guinea', 'nombre_en' => 'Guinea', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Guinea Ecuatorial', 'nombre_en' => 'Equatorial Guinea', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Guinea-Bisáu', 'nombre_en' => 'Guinea-Bissau', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Guyana', 'nombre_en' => 'Guyana', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Haití', 'nombre_en' => 'Haití', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Honduras', 'nombre_en' => 'Honduras', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Hungría', 'nombre_en' => 'Hungary', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'India', 'nombre_en' => 'India', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Indonesia', 'nombre_en' => 'Indonesia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Irak', 'nombre_en' => 'Iraq', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Irlanda', 'nombre_en' => 'Ireland', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Irán', 'nombre_en' => 'Iran', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Islandia', 'nombre_en' => 'Iceland', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Islas Marshall', 'nombre_en' => 'Marshall Islands', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Islas Salomón', 'nombre_en' => 'Solomon Islands', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Israel', 'nombre_en' => 'Israel', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Italia', 'nombre_en' => 'Italy', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Jamaica', 'nombre_en' => 'Jamaica', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Japón', 'nombre_en' => 'Japan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Jordania', 'nombre_en' => 'Jordan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Kazajistán', 'nombre_en' => 'Kazakhstan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Kenia', 'nombre_en' => 'Kenya', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Kirguistán', 'nombre_en' => 'Kyrgyzstan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Kiribati', 'nombre_en' => 'Kiribati', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Kuwait', 'nombre_en' => 'Kuwait', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Laos', 'nombre_en' => 'Laos', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Lesoto', 'nombre_en' => 'Lesotho', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Letonia', 'nombre_en' => 'Latvia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Liberia', 'nombre_en' => 'Liberia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Libia', 'nombre_en' => 'Libya', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Liechtenstein', 'nombre_en' => 'Liechtenstein', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Lituania', 'nombre_en' => 'Lithuania', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Luxemburgo', 'nombre_en' => 'Luxembourg', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Líbano', 'nombre_en' => 'Lebanon', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Madagascar', 'nombre_en' => 'Madagascar', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Malasia', 'nombre_en' => 'Malaysia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Malaui', 'nombre_en' => 'Malawi', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Maldivas', 'nombre_en' => 'Maldives', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Malta', 'nombre_en' => 'Malta', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Malí', 'nombre_en' => 'Mali', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Marruecos', 'nombre_en' => 'Morocco', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Mauricio', 'nombre_en' => 'Mauritius', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Mauritania', 'nombre_en' => 'Mauritania', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Micronesia', 'nombre_en' => 'Micronesia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Moldavia', 'nombre_en' => 'Moldova', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Mónaco', 'nombre_en' => 'Monaco', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Mongolia', 'nombre_en' => 'Mongolia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Montenegro', 'nombre_en' => 'Montenegro', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Mozambique', 'nombre_en' => 'Mozambique', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Namibia', 'nombre_en' => 'Namibia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Nauru', 'nombre_en' => 'Nauru', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Nepal', 'nombre_en' => 'Nepal', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Nicaragua', 'nombre_en' => 'Nicaragua', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Níger', 'nombre_en' => 'Niger', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Nigeria', 'nombre_en' => 'Nigeria', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Noruega', 'nombre_en' => 'Norway', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Nueva Zelanda', 'nombre_en' => 'New Zealand', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Omán', 'nombre_en' => 'Oman', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Países Bajos', 'nombre_en' => 'Netherlands', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Pakistán', 'nombre_en' => 'Pakistan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Palaos', 'nombre_en' => 'Palau', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Palestina', 'nombre_en' => 'Palestine', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Panamá', 'nombre_en' => 'Panama', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Papúa Nueva Guinea', 'nombre_en' => 'Papua New Guinea', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Paraguay', 'nombre_en' => 'Paraguay', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Perú', 'nombre_en' => 'Peru', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Polonia', 'nombre_en' => 'Poland', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Portugal', 'nombre_en' => 'Portugal', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Qatar', 'nombre_en' => 'Qatar', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Reino Unido', 'nombre_en' => 'United Kingdom', 'codigo_iso' => 'GB', 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'República Centroafricana', 'nombre_en' => 'Central African Republic', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'República Checa', 'nombre_en' => 'Czech Republic', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'República del Congo', 'nombre_en' => 'Republic of the Congo', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'República Democrática del Congo', 'nombre_en' => 'Democratic Republic of the Congo', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'República Dominicana', 'nombre_en' => 'Dominican Republic', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Ruanda', 'nombre_en' => 'Rwanda', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Rumanía', 'nombre_en' => 'Romania', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Rusia', 'nombre_en' => 'Russia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Samoa', 'nombre_en' => 'Samoa', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'San Cristóbal y Nieves', 'nombre_en' => 'Saint Kitts and Nevis', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'San Marino', 'nombre_en' => 'San Marino', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'San Vicente y las Granadinas', 'nombre_en' => 'Saint Vincent and the Grenadines', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Santa Lucía', 'nombre_en' => 'Saint Lucia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Santo Tomé y Príncipe', 'nombre_en' => 'Sao Tome and Principe', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Senegal', 'nombre_en' => 'Senegal', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Serbia', 'nombre_en' => 'Serbia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Seychelles', 'nombre_en' => 'Seychelles', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Sierra Leona', 'nombre_en' => 'Sierra Leone', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Singapur', 'nombre_en' => 'Singapore', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Siria', 'nombre_en' => 'Syria', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Somalia', 'nombre_en' => 'Somalia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Sri Lanka', 'nombre_en' => 'Sri Lanka', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Suazilandia', 'nombre_en' => 'Eswatini', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Sudáfrica', 'nombre_en' => 'South Africa', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Sudán', 'nombre_en' => 'Sudan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Sudán del Sur', 'nombre_en' => 'South Sudan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Suecia', 'nombre_en' => 'Sweden', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Suiza', 'nombre_en' => 'Switzerland', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Surinam', 'nombre_en' => 'Suriname', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Tailandia', 'nombre_en' => 'Thailand', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Tanzania', 'nombre_en' => 'Tanzania', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Tayikistán', 'nombre_en' => 'Tajikistan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Timor Oriental', 'nombre_en' => 'East Timor', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Togo', 'nombre_en' => 'Togo', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Tonga', 'nombre_en' => 'Tonga', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Trinidad y Tobago', 'nombre_en' => 'Trinidad and Tobago', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Túnez', 'nombre_en' => 'Tunisia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Turkmenistán', 'nombre_en' => 'Turkmenistan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Turquía', 'nombre_en' => 'Turkey', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Tuvalu', 'nombre_en' => 'Tuvalu', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Ucrania', 'nombre_en' => 'Ukraine', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Uganda', 'nombre_en' => 'Uganda', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Uruguay', 'nombre_en' => 'Uruguay', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Uzbekistán', 'nombre_en' => 'Uzbekistan', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Vanuatu', 'nombre_en' => 'Vanuatu', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Vaticano', 'nombre_en' => 'Vatican City', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Venezuela', 'nombre_en' => 'Venezuela', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Vietnam', 'nombre_en' => 'Vietnam', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Yemen', 'nombre_en' => 'Yemen', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Yibuti', 'nombre_en' => 'Djibouti', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Zambia', 'nombre_en' => 'Zambia', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
            ['nombre' => 'Zimbabue', 'nombre_en' => 'Zimbabwe', 'codigo_iso' => null, 'prioritario' => false, 'activo' => true, 'created_at' => $now, 'updated_at' => $now],
        ];

        // Insertar en bloques (chunks) para evitar sobrecarga de memoria
        foreach (array_chunk($paises, 50) as $chunk) {
            DB::table('paises')->insertOrIgnore($chunk);
        }
    }
}